# Generated by Django 5.2.7 on 2025-11-11 00:20

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budget_created_at_budget_total_value'),
        ('customers', '0004_alter_customer_options_alter_customer_address_and_more'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['budget_date'], 'verbose_name': 'Budget', 'verbose_name_plural': 'Budgets'},
        ),
        migrations.AlterModelOptions(
            name='budgetitem',
            options={'ordering': ['id'], 'verbose_name': 'BudgetItem', 'verbose_name_plural': 'BudgetItems'},
        ),
        migrations.RenameField(
            model_name='budgetitem',
            old_name='quantity_product',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='total_value',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='budget_id',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='total_value',
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_date',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='budget',
            field=models.ForeignKey(db_column='budget_id', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget.budget'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='product',
            field=models.ForeignKey(db_column='product_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
