# Generated by Django 5.2.7 on 2025-11-11 00:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_budget_options_alter_budgetitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
