# Generated by Django 5.2.8 on 2025-11-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_budget_budget_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='notes',
        ),
    ]
