# Generated by Django 4.2.25 on 2025-11-18 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier'),
        ('product', '0002_alter_product_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
