# Generated by Django 5.2.8 on 2025-11-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_supplier'),
        ('suppliers', '0002_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
