# Generated by Django 5.2.6 on 2025-10-28 16:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(help_text='Nome completo do funcionário', max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(help_text='E-mail único do funcionário', max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, help_text='Telefone fixo', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato: (00) 0000-0000', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')], verbose_name='Telefone')),
                ('mobile', models.CharField(help_text='Número do celular', max_length=15, validators=[django.core.validators.RegexValidator(message='Celular deve estar no formato: (00) 00000-0000', regex='^\\(\\d{2}\\)\\s\\d{5}-\\d{4}$')], verbose_name='Celular')),
                ('cpf', models.CharField(help_text='CPF no formato 000.000.000-00', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato: 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF')),
                ('rg', models.CharField(help_text='RG no formato 00.000.000-0', max_length=12, validators=[django.core.validators.RegexValidator(message='RG deve estar no formato: 00.000.000-0', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-\\d{1}$')], verbose_name='RG')),
                ('access_level', models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('employee', 'Funcionário'), ('intern', 'Estagiário')], default='employee', help_text='Nível de acesso do funcionário no sistema', max_length=10, verbose_name='Nível de Acesso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o funcionário está ativo', verbose_name='Ativo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
