# Generated by Django 5.2.6 on 2025-11-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['username'], 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='employee',
            name='bairro',
            field=models.CharField(blank=True, help_text='Bairro', max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cargo',
            field=models.CharField(blank=True, help_text='Cargo do funcionário', max_length=50, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cep',
            field=models.CharField(blank=True, help_text='CEP do funcionário', max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cidade',
            field=models.CharField(blank=True, help_text='Cidade', max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='employee',
            name='complemento',
            field=models.CharField(blank=True, help_text='Complemento do endereço', max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='employee',
            name='endereco',
            field=models.CharField(blank=True, help_text='Rua/Logradouro', max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='employee',
            name='estado',
            field=models.CharField(blank=True, help_text='UF do estado', max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='employee',
            name='numero',
            field=models.IntegerField(blank=True, help_text='Número do endereço', null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='access_level',
            field=models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('employee', 'Funcionário'), ('intern', 'Estagiário')], default='employee', help_text='Nível de acesso do funcionário no sistema', max_length=20, verbose_name='Nível de Acesso'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do funcionário', max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, help_text='Número do celular', max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone fixo', max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rg',
            field=models.CharField(blank=True, help_text='RG do funcionário', max_length=20, null=True, verbose_name='RG'),
        ),
    ]
