# Generated by Django 5.2.6 on 2025-11-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options_remove_employee_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='access_level',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Usuário', 'Usuário')], default='Usuário', help_text='Nível de acesso do funcionário no sistema', max_length=20, verbose_name='Nível de Acesso'),
        ),
    ]
