# Generated by Django 5.2.6 on 2025-10-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('rg', models.CharField(blank=True, max_length=30, null=True, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mobile')),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='ZIP Code')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Number')),
                ('complement', models.CharField(blank=True, max_length=200, null=True, verbose_name='Complement')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Neighborhood')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=2, null=True, verbose_name='State')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
    ]
