# Generated by Django 5.2.6 on 2025-10-25 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_phone_remove_customer_rg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='complement',
        ),
    ]
